// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_attempts.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFailuresSinceLastSuccess = `-- name: CountFailuresSinceLastSuccess :one
SELECT count(*)
FROM login_attempts AS failed
WHERE failed.username = $1
  AND NOT failed.succeeded
  AND failed.attempted_at > $2
  AND failed.attempted_at > COALESCE(
      (SELECT max(ok.attempted_at) FROM login_attempts AS ok WHERE ok.username = failed.username AND ok.succeeded),
      '-infinity'::timestamptz)
`

type CountFailuresSinceLastSuccessParams struct {
	Username string
	Since    pgtype.Timestamptz
}

func (q *Queries) CountFailuresSinceLastSuccess(ctx context.Context, arg CountFailuresSinceLastSuccessParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFailuresSinceLastSuccess, arg.Username, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec
INSERT INTO login_attempts (username, succeeded, ip)
VALUES ($1, $2, $3)
`

type InsertLoginAttemptParams struct {
	Username  string
	Succeeded bool
	Ip        *netip.Addr
}

func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertLoginAttempt, arg.Username, arg.Succeeded, arg.Ip)
	return err
}
