// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64
	Code      string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type LoginAttempt struct {
	ID          int64
	Username    string
	Succeeded   bool
	Ip          *netip.Addr
	AttemptedAt pgtype.Timestamptz
}

type Season struct {
	ID        int64
	Year      int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID                int64
	UserID            int64
	TokenHash         string
	CreatedAt         pgtype.Timestamptz
	LastUsedAt        pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	Ip                *netip.Addr
	UserAgent         pgtype.Text
}

type Team struct {
	ID         int64
	CategoryID int64
	Code       string
	Name       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID            int64
	Username      string
	Email         pgtype.Text
	PasswordHash  string
	Role          string
	TeamID        pgtype.Int8
	IsActive      bool
	DeactivatedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
