// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, absolute_expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateSessionParams struct {
	UserID            int64
	TokenHash         string
	AbsoluteExpiresAt pgtype.Timestamptz
	Ip                *netip.Addr
	UserAgent         pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.AbsoluteExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT s.id AS session_id, s.last_used_at, u.id AS user_id, u.username, u.role, u.team_id
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.absolute_expires_at > $2
  AND s.last_used_at > $3
  AND u.is_active
`

type GetActiveSessionByTokenHashParams struct {
	TokenHash  string
	Now        pgtype.Timestamptz
	IdleCutoff pgtype.Timestamptz
}

type GetActiveSessionByTokenHashRow struct {
	SessionID  int64
	LastUsedAt pgtype.Timestamptz
	UserID     int64
	Username   string
	Role       string
	TeamID     pgtype.Int8
}

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, arg GetActiveSessionByTokenHashParams) (GetActiveSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, arg.TokenHash, arg.Now, arg.IdleCutoff)
	var i GetActiveSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.LastUsedAt,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.TeamID,
	)
	return i, err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByTokenHash, tokenHash)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_used_at = $2
WHERE id = $1
`

type TouchSessionParams struct {
	ID         int64
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastUsedAt)
	return err
}
