// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package dbgen

import (
	"context"
)

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.code, t.name, c.code AS category_code, c.name AS category_name
FROM teams t
JOIN categories c ON c.id = t.category_id
ORDER BY c.id, t.name
`

type ListTeamsRow struct {
	ID           int64
	Code         string
	Name         string
	CategoryCode string
	CategoryName string
}

func (q *Queries) ListTeams(ctx context.Context) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CategoryCode,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamExists = `-- name: TeamExists :one
SELECT EXISTS (SELECT 1 FROM teams WHERE id = $1)
`

func (q *Queries) TeamExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, teamExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
